<?php


namespace app\api\controller\v1;

use app\common\components\Curd;
use app\common\enums\StatusEnum;
use app\common\models\sys\SysManager;
use app\common\services\sys\ManagerService;
use app\common\validate\sys\ManagerValidate;
use think\Db;

class Manager extends Base
{
    use Curd;
    public $modelClass = SysManager::class;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用户列表
     *
     * @return \think\response\Json
     */
    public function lists()
    {
        $managerList = ManagerService::ManagerList();

        return $managerList
            ? self::resultPage($managerList)
            : self::resultNotFound();
    }

    /***
     * 新增用户
     *
     * @return \think\response\Json
     */
    public function add()
    {
        // 数据接收
        $data = $this->params;

        // 数据处理
        $data['password_hash'] = md5($data['password']);
        unset($data['password']);
        // 数据规则验证
        $validate = new ManagerValidate;
        if (!$validate->check($data)) {
            return self::resultMsg(422, $validate->getError(), $data);
        }

        // 数据模型
        $model = new $this->modelClass;

        // 保存数据
        return $model->save($data)
            ? self::resultMsg(200, $model->id)
            : self::resultMsg(422, $model->getError());
    }

    /**
     * 修改用户信息
     *
     * @return \think\response\Json
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function edit()
    {
        // 数据接收
        $data = $this->params;

        if (empty(($model = SysManager::where('id', $data['id'])->find()))) {
            return self::resultMsg(404, '未找到数据或您的权限不足');
        }
        // 数据处理
        $data['password_hash'] = md5($data['password']);
        unset($data['password']);
        // 数据规则验证
        $validate = new ManagerValidate;
        if (!$validate->scene('edit')->check($data)) {
            return self::resultMsg(422, $validate->getError(), $data);
        }

        // 保存数据
        return $model->save($data)
            ? self::resultMsg(200, $model->id)
            : self::resultMsg(422, $model->getError());
    }

    /***
     *  用户状态更改
     *
     */
    public function switchStatus()
    {
        $data = $this->params;

        $flag = $data['flag'];

        switch ($flag) {
            case StatusEnum::ENABLED :
                break;
            case StatusEnum::DISABLED :
                break;
            case StatusEnum::DELETE :
                break;
            default:
                return self::resultMsg(422, '类型错误');
        }

        // 启动事务
        Db::startTrans();
        try {
            if (empty(($model = SysManager::where('id', $data['id'])->find()))) {
                throw new \Exception('未找到数据或您的权限不足!');
            }

            $model->status = $flag;
            $model->save();
            // 提交事务
            Db::commit();
            return self::resultMsg(200, '状态更改成功');
        } catch (\Exception $e) {
            // 回滚事务
            Db::rollback();
            return self::resultMsg(422, $e->getMessage());
        }

    }
}