<?php

namespace app\api\controller\v1;

use app\common\models\sys\SysMenu;
use app\common\validate\sys\MenuValidate;
use app\common\services\sys\MenuService;
use app\common\components\Curd;

class Menu extends Base
{
    use Curd;
    public $modelClass = SysMenu::class;

    protected function _initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function lists ()
    {
        $menuList = MenuService::MenuList();

        return $menuList
            ? self::resultPage($menuList)
            : self::resultNotFound();
    }

    public function updateList()
    {
        $data = $this->params;

        $result = $this->validate(
            $data,
            'app\common\validate\sys\MenuValidate');

        if (true !== $result) {
            // 验证失败 输出错误信息
            return self::resultMsg(422, $result);
        }
        $model = $this->findModel($data['id']);

        return $model->save($data)
            ? self::resultMsg(200, $model->id)
            : self::resultMsg(422, $model->geterror());
    }


}